### ISSUE TITLE
Support for regex flags

### ISSUE THREAD

**Issue by jbaileyashe** [propensive/kaleidoscope#14]
The macro seems to misinterpret flags at the beginning of a regex when capturing results. When `regexTest1` matches below, you get an `IndexOutOfBoundException`. When `regexTest1` does not match, no error occurs. When `regexTest2` matches, no error occurs.

I'm using kaleidescope 0.1.0. LOVE this library - if possible could you please release an update to Maven Central?

```scala
import kaleidoscope._
object RegexTest {
  def regexTest1(s: String) = s match {
    case r"(?i)$c@(foo)" => Option(c: String)
    case _ => None
  }

  def regexTest2(s: String) = s match {
    case r"$c@(foo)" => Option(c: String)
    case _ => None
  }
}

scala> RegexTest.regexTest1("foo")
java.lang.IndexOutOfBoundsException: No group 2

scala> RegexTest.regexTest1("bar")
res3: Option[String] = None

scala> RegexTest.regexTest2("foo")
res2: Option[String] = Some(foo)
```

**Comment by propensive** [comment]
Thanks for the positive feedback, @jbaileyashe! I had never actually used flags in a regular expression before...

I had a quick look at the code, and the fix is not entirely trivial, but would make a good issue for someone who doesn't mind messing around with a recursive method that's parsing a string.

I'm looking to get a new release of Kaleidoscope out around the same time as [Fury](https://github.com/propensive/fury/) which is "as soon as possible".

**Comment by jbaileyashe** [comment]
Would love to help but the `make` based build system isn't Windows friendly so I'm not sure how I'd run tests :(
